image: python:3.10-slim

stages:
  - build
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  MAJOR: "V1"
  PIPELINE_SEQUENCE: $CI_PIPELINE_IID

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build-job:
  stage: build
  script:
    - pip3 install build wheel
    - python3 -m build . --wheel
    - pip3 install .[test,lint]

unit-test-job:
  stage: test
  script:
    - export PYTHONPATH=./app
    - pytest -v tests

lint-test-job:
  stage: test
  script:
    - which flake8
    - flake8 --config=setup.cfg

deploy-gitlab-job:
  image: docker:23.0.1
  stage: deploy
  services:
    - docker:23.0.1-dind
  variables:
    PROJECT_NAME: "python-fastapi-template" # TODO: 프로젝트명에 맞게 수정
  before_script:
    - VERSION=$MAJOR.$CI_COMMIT_SHORT_SHA
    - IMAGE_TAG=$CI_REGISTRY_IMAGE/$PROJECT_NAME:$VERSION
    - IMAGE_TAG_LATEST=$CI_REGISTRY_IMAGE/$PROJECT_NAME:latest
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST
  only:
    - main