stages:
  - secret_detection
  - lint
  - test
  - check_app_runnable
  - deploy

include:
  - local: /.gitlab/ci/secret-detection.gitlab-ci.yml
  - local: /.gitlab/ci/lint.gitlab-ci.yml
  - local: /.gitlab/ci/test.gitlab-ci.yml
  - local: /.gitlab/ci/container-test.gitlab-ci.yml
  - local: /.gitlab/ci/deploy.gitlab-ci.yml