# 해당 파이프라인은 GitLab CI Template 프로젝트에서 가져와서 설정하기 때문에 프로젝트 접근 권한이 있어야합니다.
# 만약 접근 권한이 없을 경우, 해당 CI 파일을 직접 가져와서 로컬에서 사용해도 됩니다.
# 또한 GitLab CI 파이프라인은 overriding이 가능하기때문에 템플릿을 가져와서 커스텀을 할 수도 있습니다.
# 참고: https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
  - secret_detection
  - lint
  - test
  - build-and-push-app
  - container_test

include:
  - project: wisenut-research/starter/gitlab-ci-template
    ref: main
    file:
      - templates/Security/Secret-Detection.gitlab-ci.yml
      - templates/Python/Dependency-Management.gitlab-ci.yml
      - templates/Python/Lint.gitlab-ci.yml
      - templates/Python/Test.gitlab-ci.yml
      - templates/Security/Container-Scanning.gitlab-ci.yml
      - templates/Python/Build-and-Push-App.gitlab-ci.yml

# Overrides
.dependency-management:
  image: python:3.10.16-slim


build-and-push-app:
  tags:
    - saas-linux-medium-amd64  # 16GB Memory, 50GB storage

ruff-lint:
  parallel:
    matrix:
      - PYTHON_VERSION: [ "py310" ]

pyright-lint:
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.10" ]

pytest-39:
  rules:
    - when: never

pytest-311:
  rules:
    - when: never

pytest-312:
  rules:
    - when: never
