[build-system]
requires = [
    "setuptools >= 61.0.0",
    "wheel >= 0.37.1"
]
build-backend = "setuptools.build_meta"


[project]   # TODO: 프로젝트 메타데이터 작성 (되도록이면 main.py의 app과 동일한 name, version, description으로 작성하기)
name = "python-fastapi-template"
version = "v1"  # major 버전만 기입
authors = [
    { name = "Seoyeon Park", email = "sally9476@wisenut.co.kr" }
]
maintainers = [
    { name = "Moonjong Kim", email = "penbell@wisenut.co.kr" },
    { name = "Chanyeong Lee", email = "wisnt65@wisenut.co.kr" },
    { name = "Seoyeon Park", email = "sally9476@wisenut.co.kr" },
    { name = "Joongheon Jeong", email = "legagain@wisenut.co.kr" }
]
description = "DE Team Python FastAPI Template"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
keywords = ["python", "fastapi", "template"]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Framework :: FastAPI",
    "Natural Language :: Korean",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP",
    "Intended Audience :: Developers"
]
dependencies = [
    "anyio==3.6.2",
    "click==8.1.3",
    "colorama==0.4.6",
    "fastapi==0.95.2",
    "greenlet==2.0.2",
    "h11==0.14.0",
    "idna==3.4",
    "loguru==0.7.0",
    "pydantic==1.10.7",
    "PyYAML==6.0",
    "sniffio==1.3.0",
    "SQLAlchemy==2.0.13",
    "starlette==0.27.0",
    "toml==0.10.2",
    "typing_extensions==4.5.0",
    "uvicorn==0.22.0",
    "win32-setctime==1.1.0"
]

[project.optional-dependencies]
test = [
    "pytest >= 7.3.1",
    "httpx >= 0.24.0"
]
lint = [
    "mypy == 1.3.0",
    "ruff >= 0.0.278",
    "pyright >= 1.1.316"
]

[tool.setuptools]
py-modules = ["app"]    #TODO: 패키징할 패키지 선언 (현재는 MSA 구조인 app을 패키지 디렉토리로 선언)


[tool.ruff]
ignore = ['W']
line-length = 125
exclude = [
    '.git',
    '__pycache__',
    '.mypy_cache',
    '.ruff_cache',
    'docs',
    'venv',
    'tests',
    'build',
    'dist'
]
target-version = "py39"
[tool.ruff.mccabe]
max-complexity = 10


[tool.mypy]
plugins = [
    'pydantic.mypy'
]
python_version = "3.9"
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = false # true시 ignore 처리 error로 뜨게 함
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true
warn_return_any = true
warn_unused_configs = true
exclude = [
    '.git',
    '__pycache__',
    '.mypy_cache',
    '.ruff_cache',
    'docs',
    'venv',
    'tests',
    'build',
    'dist',
    '^app\\src\\keyword_extraction\\tf_isf.py$'
]
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
[[tool.mypy.overrides]]
module = [
    "kiwipiepy",
    "keybert",
    "toml",
    "yaml",
    "version_info"
]
ignore_missing_imports = true


[tool.pyright]
include = ["app"]
exclude = [
    '.git',
    '__pycache__',
    '.mypy_cache',
    '.ruff_cache',
    '.pytest_cache',
    'docs',
    'venv',
    'tests',
    'build',
    'dist',
    'pypi',
    'logs',
    'app/src/keyword_extraction/tf-isf'
]
defineConstant = { DEBUG = true }
reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.9"
