# 해당 파일은 CI에 해당하는 secret-detetction에 커스텀으로 설정할 수 있는 파일입니다.
# 간단한 예제로 참고만하고 새로운 룰이 필요할 경우, 추가하시면 됩니다.
# 참고: https://about.gitlab.com/blog/2021/12/21/rule-pack-synthesis/

[secrets]
  [[secrets.ruleset]]
    disable = true
    [secrets.ruleset.identifier]
      type = "gitleaks_rule_id"
      value = "Password in URL"
  [[secrets.passthrough]]
    type  = "file"
    # note this must be gitleaks.toml
    target = "gitleaks.toml"
    value = "config/gitleaks.toml"