site_name: Wise Docs
site_dir: public
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
  favicon: ./images/wisenut_icon.ico
  logo: ./images/wisenut_logo.png
markdown_extensions:
  # code block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
# 'mike' for versioning
extra:
  version:
    provider: mike
nav:
  - HOME: './index.md'
  - Quick start: './start/quickstart.md'
  - Getting Started: './start/getting-started.md'
  - Guide:
    - MSA: './guide/msa.md'
    - GitLab CI/CD pipeline: './guide/ci-cd.md'
    - Gunicorn: './guide/gunicorn.md'
    - Automation-bot: './guide/automation-bot.md'
    - Mkdocs: './guide/mkdocs.md'
  - API: './api/docs.html'

plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: 'public'
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
