include:
  - local: /.gitlab/ci/container-test.gitlab-ci.yml

deploy-gitlab-job:
  extends: .container
  stage: deploy
  script: # docker image cache를 사용하여 이미지 빌드, 컨테이너 레지스트리 푸시 진행
    - docker pull $IMAGE_TAG_LATEST || true # 마지막 이미지 가져오기
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG_LATEST -t $IMAGE_TAG -t $IMAGE_TAG_LATEST . # 마지막 이미지를 캐시로 사용
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST