.test:
  stage: test
  image: python:3.9.13-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PIPELINE_SEQUENCE: $CI_PIPELINE_IID
    TZ: "Asia/Seoul"
    FF_TIMESTAMPS: true
  cache:
    paths:
      - .cache/pip
      - venv
      - .mypy_cache/
  before_script:
    - echo "Running before_script tasks for $CI_JOB_NAME";
    - python3 -V
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.create false --local
    - poetry install --no-root

ruff-lint-test-job:
  extends: .test
  script:
    - ruff check .

mypy-lint-test-job:
  extends: .test
  script:
    - mypy .

pyright-lint-test-job:
  extends: .test
  script:
    - pyright ./

unit-test-job:
  extends: .test
  script:
    - |
      set -o allexport
      source .env
      VERSION=${MAJOR_VERSION}.$(date +'%y%m.%d')-${STATUS}-$CI_COMMIT_SHORT_SHA
      set +o allexport
    - BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')
    - export PYTHONPATH=./app
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml -v tests
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
