# 한 job을 버전별로 테스트 할 수 있는 방법은 2가지가 있음
# (현재 템플릿에서는 파이썬 버전 호환 테스트를 위한 방법으로 사용)
# 1. lint.gitlab-ci.yml 파일의 ruff-lint-test-job의 parallel.matrix.${env}
# 2. test.gitlab-ci.yml 파일에서 extends를 통해 image만 변경
# 이 두 가지 방식으로 진행할 수 있으니 편한 방식을 채택해서 사용하길 바람

.unit-test:
  extends: .lint
  stage: test
  script:
    - |
      set -o allexport
      source .env
      VERSION=${MAJOR_VERSION}.$(date +'%y%m.%d')-${STATUS}-$CI_COMMIT_SHORT_SHA
      set +o allexport
    - BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')
    - export PYTHONPATH=./app
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml -v tests
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pytest-39:
  extends: .unit-test
  image: python:3.9-slim
pytest-310:
  extends: .unit-test
  image: python:3.10-slim
pytest-311:
  extends: .unit-test
  image: python:3.11-slim
pytest-312:
  extends: .unit-test
  image: python:3.12-slim

sast:
  stage: test